### ISSUE TITLE
Show the names of regions only or larger

### ISSUE THREAD

**Issue by strongpauly** [farling42/fvtt-easy-regions#5]
IMHO it would be better to show the names of the `Scene => Region` only or at least larger than the UUID reference.  Users don't care about UUIDs (a fact which the core foundry team seem to have missed with this feature).

Great module!  Love how its coming along.

**Comment by farling42** [comment]
Thanks for the suggestion.

Unfortunately, it is entirely up to the browser (Chrome or Foundry) to decide how to display the drop-down menu. There is limited control available even with CSS to be able to control how the drop-down menu is displayed.

I would much rather see the label as the main text and the value in the smaller font, but I don't know if it is possible.

**Comment by farling42** [comment]
Just for my own notes:

- Impossible to style how the `datalist` is presented when attached to an input. According to the HTML specification, it is an O/S implementation, not a browser implementation.

- Impossible to replace the "input" element inside Foundry's HTMLDocumentTagsElement with a select element, because foundry stores it's input element in a private variable (`#input`) and adds a private event handler to it (`#tryAdd`).

- Impossible to replace Foundry's HTMLDocumentTagsElement with our own variant, because foundry calls `foundry.applications.elements.HTMLDocumentTagsElement.create` which isn't overrideable.

**Comment by farling42** [comment]
I briefly started up Firefox, and it presents the list by only displaying the names of the regions.

It seems like it is a really bad implementation within Chrome which is displaying the drop-down in that horrible manner.

**Comment by farling42** [comment]
Custom dropdown list handling has been added in https://github.com/farling42/fvtt-easy-regions/releases/tag/0.7.2
