### ISSUE TITLE
[Feature Request] Show distance cost on normal token measurement in PF2e

### ISSUE THREAD

**Issue by pedrogrullada** [farling42/fvtt-easy-regions#7]
I don't use the Drag Measurement option. Would it be possible for movement cost to display using normal token measuring? Thanks for the module!

**Comment by farling42** [comment]
My module option simply adds additional information to the label that is already being displayed by PF2e's drag ruler.
It would be a lot more work for me to implement my own drag mechanism.
It might be possible for you to set the drag ruler colour to some totally transparent colour so that the line isn't drawn.
